name = "󰀈 Bestiary 󰀈"
description = "None"
author = "-т-"
version = "0.0.1"
forumthread = ""
icon_atlas = "icon.xml"
icon = "icon.tex"
client_only_mod = false
all_clients_require_mod = true
dst_compatible = true
dont_starve_compatible = false
priority = 0
api_version = 10